name: astro
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.19
  - numpy=2.2.6
  - pandas=2.3.3
  - scipy=1.15.3
  - matplotlib-base=3.10.8
  - pip:
      - astropy==6.1.7
      - astroquery==0.4.11
      - lightkurve==2.5.1
      - tenacity==9.1.4
      - scikit-learn==1.7.2
      - torch==2.10.0+cpu
      - torchaudio==2.10.0+cpu
      - torchvision==0.25.0+cpu
      - pyarrow==24.0.0
      - jupyterlab==4.5.4
      - tqdm==4.67.3
